Mobile first
JansueT/Portfolio pull request #1
Opened 2022-12-02 11:21 UTC by JansueT

2022-12-02 17:52 UTC, iambenkis requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @JansueT 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project, but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Required Changes ♻️

- [ ] You should stick to the design as much as possible (e.g. font, colours, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1).

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-02 17:52 UTC, iambenkis commented on index.html
> +    </nav>
- [ ] Good job @JansueT :+1: , however the link to the hamburger image is broken. Kindly provide a proper url :pray: 

Your design
 
![Screenshot from 2022-12-02 19-31-28](https://user-images.githubusercontent.com/80458199/205352126-dd3f7219-28e8-4e62-abb8-3cff9bb58962.png)

2022-12-02 17:52 UTC, iambenkis commented on index.html
> +          </a>
- [ ] Good job @JansueT :+1: , however the link to the hamburger image is broken. Kindly provide a proper url :pray: 

Your design

![Screenshot from 2022-12-02 19-31-46 (1)](https://user-images.githubusercontent.com/80458199/205352335-5cd359b3-422e-4f44-a094-2f4a0a2de8c2.png)

2022-12-02 17:52 UTC, iambenkis commented on index.html
> +    <div class="addline_social">
- [ ] I appreciate the effort you put in implementing your design, but your design should stick as much as possible to the Figma design :100:. That means you should make sure to check if the attribute such as ```font-family```, ```color```, ```margin```, ```font-weight``` etc are the same in your design as in the Figma design. :smile: 
- [ ] Kindly make sure the ```font-family``` look the same in your design as given in the Figma design :health_worker: 

Your design:

![Screenshot from 2022-12-02 19-46-32](https://user-images.githubusercontent.com/80458199/205354117-9ca64bca-526d-493b-8524-338d83d41b61.png)

The Figma design

![Screenshot from 2022-12-02 19-47-13](https://user-images.githubusercontent.com/80458199/205354197-164420db-a93d-4e5d-b346-5af30c1c75d8.png)

2022-12-03 11:49 UTC, Debas-31 approved these changes
> ## Hi @JansueT  :wave:, 

# Status: Approved :heavy_check_mark: 

Great work on making the changes requested by a previous reviewer. Your project is complete !  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/fYlennPcKut8gjKOZD/giphy.gif"/>

## Highlights
- PR title and summary :heavy_check_mark: 
- Commit message :heavy_check_mark:
- Figma template usage :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 12:15 UTC, merged

2023-02-18 10:55 UTC, Felix45 reviewed
# Approved :green_circle: 
Hi @JansueT , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://camo.githubusercontent.com/9ab1354ab399a31c604186cd2e7c09a0d4704215a1eda3e29a02fc52bf3f6bf5/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6d474b31673838485a526132466c4b47627a2f67697068792e676966" />

## Highlights :heavy_check_mark: 
- [ ] No linter error :white_check_mark: 
- [ ] GitHub flow is used correctly :white_check_mark: 
- [ ] Descriptive pull request summary :white_check_mark: 

## Optional suggestions
- [ Optional ] Please consider adding a `License` file in your project directory and also add a link to the License file on the `readme` file. It's considered good practice to always have a License in your project to inform people who would like to use your code how it is Licensed. Once you've added the link to the License, you can remove the `NOTE` section under the License link.

![Screenshot from 2023-02-18 13-51-26](https://user-images.githubusercontent.com/16392046/219856444-cd26aa9c-4094-4392-bced-eab3786fcf99.png)

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 07:29 UTC, AlphaNtihinduka reviewed
# STATUS: APPROVED :green_circle: :clap: 
## Hi @JansueT 🙋‍♂️, 

Your project is complete!  There is nothing else to say other than... Great job 👏 

![approved-accepted](https://user-images.githubusercontent.com/99394374/212473432-e725752b-8682-4dbb-993e-9e466dbe7acb.gif)

Congratulations! 🎉 
TO HIGHLIGHT:

- Your project is professional :heavy_check_mark: 
- Your repo is professional :heavy_check_mark: 
- Well-structured files :heavy_check_mark: 
- Professional README.md file 💯
- No linter errors :heavy_check_mark: 

Now you can merge this branch and move on :1st_place_medal: 


## Optional suggestions
- [ ] [ Optional ] Please consider adding a License file in your project directory and also add a link to the License file on the readme file. It's considered good practice to always have a License in your project to inform people who would like to use your code how it is Licensed. Once you've added the link to the License, you can remove the NOTE section under the License link.
- _Kindly refer to the inline optional suggestions made. Ensure to apply them to have a professional project that suits recruiters' needs._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

HAPPY CODING AND GOOD LUCK WITH THE COMING ONES :crossed_fingers: :four_leaf_clover: