Desktop version
JansueT/Portfolio pull request #5
Opened 2022-12-16 14:59 UTC by JansueT

2022-12-16 17:38 UTC, Gambit142 requested changes
Hi @JansueT 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- README.md file is professional ✔️ 
- Pull request title and description is descriptive ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

#### Please note that when you are implementing the changes I suggested for this milestone, your mobile version should remain intact and identical to the Figma template that you chose 👍 

_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-12-16 17:38 UTC, Gambit142 commented on index.html
>      <section class="headline">
- [ ] For the `headline` section, kindly make your design look identical to that of the Figma template you chose. To make it look identical, kindly work on:

- The background images used
- The `hx` elements with texts `"Hey there. I’m Cansu"` and `"I'm a software developer"`
- The dropdown icon used 💻 

### Your Design

![image](https://user-images.githubusercontent.com/77106962/208150819-8a5a17a8-0726-4660-893d-5f7dae6a3eec.png)

### Figma Template

![image](https://user-images.githubusercontent.com/77106962/208151065-5ab557b1-341a-412b-9d28-ebf834569bdd.png)

2022-12-16 17:38 UTC, Gambit142 commented on index.html
>          </div>
- [ ] For the recent `About Myself` section, kindly make this section look identical to that of the Figma template you chose. To highlight the changes to be made in this section, you need to:

- Make the `Languages`, `Framework` and `Skills` subsections align on a row. 
- Use the background images used for this section and align the accordingly
- Alignment and structure of the `p` element with the text `"I can help you build a product ..."`
- The alignment of each card and its badges. 👍 

### Your Design

![image](https://user-images.githubusercontent.com/77106962/208153934-9992c382-b833-4c3e-bca9-831148117902.png)

### Figma Design

![image](https://user-images.githubusercontent.com/77106962/208153801-56e21544-db4e-4835-aed5-c0f0f7ccb8d3.png)


#### Hint: Use the `grid` to style the section and then `flexbox` to style individual cards 👍

2022-12-16 17:38 UTC, Gambit142 commented on index.html
>          <div class="img2"></div>
- [ ] For the recent `Form` section, kindly make this section look identical to that of the Figma template you chose. To highlight the changes to be made in this section, you need to:

- The `form` and the `p` elements should be on a row. The `form` element should be on the right side while the `p` element with the text `"I'm always interested in hearing ..."` should be on the left side. 💻 
- The background images used should be present and well aligned
- The social media icons are at the center and aligned with the correct margin between each icon 👍 

### Your Design

![image](https://user-images.githubusercontent.com/77106962/208155177-c12f4702-923c-48c9-a5cf-7fee2312d5a8.png)

### Figma Design

![image](https://user-images.githubusercontent.com/77106962/208155268-1decc056-d6f1-43dd-9aa7-e2ae734d66ba.png)

#### P.S: The form input for the full name is two (first and last name) for the desktop version of the design on Figma. However, due to the requirement, you should have one input for the full name, so you do not have to implement it the same way it is implemented on Figma.

![image](https://user-images.githubusercontent.com/77106962/208155847-a2f95930-f82c-4625-a5de-95354b69c419.png)

2022-12-17 17:40 UTC, JansueT commented
I made all of the changes which requested from the previous code viewer.

2022-12-17 19:06 UTC, brainconnect93 requested changes
### Hi @JansueT, 👋 

# STATUS: Changes Required :recycle:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight :1st_place_medal: 
-  Has a proper Pull Request. ✔️  
- No Linter errors :heavy_check_mark: 
- Good use of Github flow ✔️ 

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

- [x] **[OPTIONAL but Highly recommended] Great effort working on your portfolio project 👏 👏 👏 , I must commend that you have done amazingly well. But I could realize that while make those effort  working on your `desktop version` , you have introduced a lot of errors in your `mobile version` which has made it distrupted and not well `aligned` with the `mobile screen size` of  `375px`. I would suggest you kindly Fix this as the goal of this `MILESTONE` is to have your `portfolio` project working perfectly on both `mobile screen` as well as `desktop screen`. Thanks and see you.**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-17 21:23 UTC, JansueT commented
<img width="788" alt="Screenshot 2022-12-18 001942" src="https://user-images.githubusercontent.com/111116267/208266388-47806067-7299-45b1-a251-be61d2990c9c.png">

@brainconnect93 Thank You for the code review.

- I did all of requested changes.

2022-12-17 21:51 UTC, MeqdamAlqudah approved these changes
Hi @hakichris , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![image](https://media1.giphy.com/media/n58MqIchLqAalRQAQB/giphy.gif?cid=790b7611f767eb90048b879a77526eadec5abad2707b9c5c&rid=giphy.gif&ct=g)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-17 21:51 UTC, MeqdamAlqudah commented on style.css
> +  }
- [Optional] Please make sure that the web page is responsive look how it looks like when  the screen size is changed, I suggest you use more responsive sizing, like VW (try to use one responsive size in all the projects like vw for all the page) which represent the size depending on the screen width   I suggest you take a look at this [website](https://web-development.space/tools/px-to-vw/) compare the size in the design using this [website](https://web-development.space/tools/px-to-vw/)
- 
![image](https://user-images.githubusercontent.com/74744787/208267050-4cf853d7-2590-47a1-998c-2f2d121f9e3f.png)

2022-12-17 21:52 UTC, merged

2023-02-22 09:37 UTC, TuyishimireEric commented
# Status: APPROVED 🟢  
### Hi  @hakichris  👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job so implementing the project requirements! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉 

## Highlights
✔️professional PR👍 
✔️professional README👍 
✔️Codes are clean👍 

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-02 11:10 UTC, mckent05 reviewed
Hi @JansueT, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._